### ISSUE TITLE
Correlating systematics in config

### ISSUE THREAD

**Issue by alexander-held** [alexander-held/cabinetry#213]
The config should provide a method for correlating different systematic uncertainties. One way to achieve this is a new option for the name of the modifier in the `pyhf` workspace, for example like this:
```yaml
Systematics:
  - Name: "Modeling_Background"
    ModifierName: "Modeling"
    Up:
      Weight: "weight_up"
    Down:
      Weight: "weight_down"
    Samples: "Background"
    Type: "NormPlusShape"

  - Name: "Modeling_Signal"
    ModifierName: "Modeling"
    Up:
      Weight: "weight_up"
    Down:
      Weight: "weight_down"
    Samples: "Signal"
    Type: "NormPlusShape"
```

The systematics would show up as modifiers in the workspace with name `Modeling`, and `Modeling_Background` or `Modeling_Signal` would never appear there. This allows to still use the `Name` value as a unique identifier per systematic within `cabinetry`. The `ModifierName` value should only be required when creating the workspace within the `workspace` module.
