### ISSUE TITLE
Templates for variation of more than one parameter

### ISSUE THREAD

**Issue by alexander-held** [alexander-held/cabinetry#51]
`HistFactory` deals with templates that describe the distribution of a sample when varying a single parameter (corresponding to a systematic uncertainty). For two parameters `(a, b)`, usually four templates are provided for these points: `(1,0)`, `(-1,0)`, `(0,1)`, `(0,-1)`.

As suggested by @cranmer, it would be good to make `cabinetry` flexible enough to support a more general scenario where templates can correspond to variations of multiple parameters at the same time. As an example, it should be possible to provide a template corresponding to `(1,1)`.

The following two things are needed for this:
- A way to implement this in the config file. At the moment, users specify systematics, and the associated templates show variations of the parameter describing the systematic. All systematics naturally factorize in the config file. If templates corresponding to variations of multiple parameters are needed, then maybe a list of systematics and a list of templates could be used. The systematics list could describe general aspects of each systematic (e.g. what samples it acts on), and the list of templates could specify how to obtain a given template and to what parameter settings it corresponds to. This could make the config significantly less readable, and better solutions might exist.
- A structure within `cabinetry` that associates templates to systematics and passes them on to a tool that would use them.

**Comment by alexander-held** [comment]
Some ideas about a configuration file structure are [in this gist](https://gist.github.com/alexander-held/57a3f65859d2b50e40762037c69b51e2). Conceptually, it seems like a good idea to group together everything that is related to template interpolation: systematic variations, but also e.g. signal template variations for things like mass measurements.

The following structure is one possibility:
```yaml
TemplateInterpolation:
  UpDownSystematics:  # equivalent to the current "Systematics" block
    - Name: "Luminosity"
      ...
      Type: "Normalization"

    - Name: "Modeling"
      ...

  ExtendedHistFactorySystematics:  # nuisance parameter values do not have to be -1, 1
    - Name: ""
      ...

  DirectProductSystematics:  # templates for direct product of multiple parameters
    - Name: ""
      ...

  MeshgridSystematics:  # templates at any value of multiple parameters
    - Name: ""
       ...

  Other:  # need some other name for remaining cases, like different signal mass templates
    - Name: ""
      ...
```
